dist: xenial
language: minimal
addons:
  apt:
    packages:
    - qemu
cache:
  directories:
    - vendor
env:
  global:
    - PACKER_VERSION="1.4.0"
    - PACKER_CACHE_DIR="vendor"
script:
  - sudo ./build.bash
